package(default_visibility = ["//visibility:public"])

# C++ binary that uses the nanopb library
cc_binary(
    name = "main",
    srcs = ["main.cpp"],
    deps = [
        "//proto:simple_nanopb_proto",
    ],
)
